### ISSUE TITLE
Do kprove on CircleCI

### ISSUE THREAD

**Issue by yudetamago** [LayerXcom/verified-vyper-contracts#42]

**Comment by nrryuya** [comment]
We need a command which creates the summary of the results of all specs.

**Comment by yudetamago** [comment]
If possible, it is useful to save detailed execution debug logs for later use.

**Comment by nrryuya** [comment]
Also I want to pass option of kprove like `make erc20/balanceOf-spec.k.test --log-basic`

**Comment by yudetamago** [comment]
TODO
* How to modify `hashedLocation` ( https://github.com/LayerXcom/verified-vyper-contracts/tree/master/k#hashedlocation ) non-interactively?
* Do in specific branch or only changed files?

**Comment by nrryuya** [comment]
I'm OK about using forked KEVM, not only in CI.

**Comment by yudetamago** [comment]
Thanks! I'll try with the commit

**Comment by nrryuya** [comment]
#54
