### ISSUE TITLE
Korean translation

### ISSUE THREAD

**Issue by hskang9** [LayerXcom/verified-vyper-contracts#83]
Hey @nrryuya, I would like to introduce your work on [Ethcon Korea](https://ethcon.kr/), and get some more developers to work on this. Is it okay if I use your codebase as a tutorial with Korean translation?

![image](https://user-images.githubusercontent.com/12888144/58355693-3597de80-7eb0-11e9-9318-f837d4a5cef8.png)

**Comment by nrryuya** [comment]
Sure! Thanks.
I'm not actively working on this these days but any contribution is welcome!
